apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

name: root-a
version: 1.0.0

imports:
- key: imp-a
  type: string

exports:
- key: exp-a
  type: string

executors: | # has to be idempotent
  - name: main
    type: Mock
    config:
      providerStatus:
        imp: {{ index .imports "imp-a" }}
      export:
        exp-a: exp-mock
