apiVersion: landscaper.gardener.cloud/v1alpha1
kind: ComponentDefinition
metadata:
  name: nginx-ingress-controller
spec:

  customTypes:
  - name: string
    openAPIV3Schema:
      type: string

  imports:
  - key: .kubeconfig
    type: kubeconfig

  - key: .helmchart.ingress-controller
    type: helmchart
  - key: .images.nginx-ingress-controller
    type: image

  - key: .dnsClass
    type: string
  - key: .resources
    type: ResourceRequirements
    required: false

  exports:
  - key: .ingressClass # from effective helm values as DeployItem's export
    type: string

  executor: # has to be idempotent
  - type: template
    config:
      template:
        type: helm
        providerConfig: |
          chartRepository: {{ .imports.helmchart.ingress.controller.chartRepository }}
          version: {{ .imports.helmchart.ingress.controller.version }}
          kubeconfig: {{ .imports.kubeconfig }}
          values:
            ingressClass: nginx
            image:
              repository: {{ .imports.images.nginx-ingress-controller.repository }}
              tag: {{ .imports.images.nginx-ingress-controller.tag }}
            dnsControllerClass: {{ .imports.dnsClass }}
            {{ if .imports.resources }}
            resources:
              requests:
                cpu: {{ .imports.resources.requests.cpu }}
                memory: {{ .imports.resources.requests.memory }}
            {{ end }}
