apiVersion: landscaper.gardener.cloud/v1alpha1
kind: BlueprintReference

name: dns-controller # defaulted to the name of the component
ref: dns-controller:0.10.5 # will be translated by the component descriptor to eu.gcr.io/gardener-project/definitions/dns-controller:0.10.5

# import, export mappings
exports:
- from: dnsClass
  to: dnsClass

staticData:
- values:
    abc: true
- value:
    secretRef: abc
- values:
    local: ./configfile.yaml