apiVersion: landscaper.gardener.cloud/v1alpha1
kind: BlueprintReference

name: nginx-ingress-controller # defaulted to the name of the component
ref: nginx-ingress-controller:0.5.0
imports:
- from: ext.dnsClass
  to: dnsClass
exports:
- from: nginxIngressClass
  to: ingressClass