apiVersion: landscaper.gardener.cloud/v1alpha1
kind: DeployItem
metadata:
  name: export
spec:
  type: Container

  config:
    apiVersion: container.deployer.landscaper.gardener.cloud/v1alpha1
    kind: ProviderConfiguration

    image: alpine
    command: ["sh", "-c"]
    args:
    - |
      env
      echo '{ "my-val": true }' > $EXPORTS_PATH
      cat $EXPORTS_PATH

    importValues: abc
