apiVersion: landscaper.gardener.cloud/v1alpha1
kind: DeployItem
metadata:
  name: state
spec:
  type: landscaper.gardener.cloud/container

  config:
    apiVersion: container.deployer.landscaper.gardener.cloud/v1alpha1
    kind: ProviderConfiguration

    image: alpine
    command: ["sh", "-c"]
    args:
    - |
      env
      ls -la $STATE_PATH
      echo '{ "my-val": true }' > $STATE_PATH/test
      ls -la $STATE_PATH

    importValues: abc
