apiVersion: landscaper.gardener.cloud/v1alpha1
kind: DataType
metadata:
  name: image

scheme:
  openAPIV3Schema:
    type: object
    properties:
      name:
        type: string
      repository:
        type: string
      tag:
        type: string
