apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Type
metadata:
  name: image
spec:
  openAPIV3Schema:
    type: object
    properties:
      name:
        type: string
      repository:
        type: string
      tag:
        type: string
