apiVersion: landscaper.gardener.cloud/v1alpha1
kind: ComponentDefinition
metadata:
  name: nginx-ingress-controller
spec:

  imports:
  - key: .kubeconfig
    type: kubeconfig

  - key: .helmchart.gardener-installer-controller
    type: helmchart
  - key: .images.gardener-installer-controller
    type: image

  - key: .dnsClass
    type: string
  - key: .resources
    type: ResourceRequirements
    required: false

  exports:
  - key: .ingressClass # from effective helm values as DeployItem's export
    type: string

  executor: | # has to be idempotent
    - name: annotate
      type: script
      config:
        script: kubectl annotate project confirmations=xyz
    - name: create-bucket
      type: terraform
    - name: deploy-etcd
      type: helm
    - name: deploy-apiserver
      type: helm

    {{ if .abc }} # templating engine of choice => go template (sprig) | spiff++ | makorender | lua | velocity
    - name: abc
      type: DeployerInstallation
      config:
        template:
          type: Helm
          providerConfig:
            chartRepository: {{ .imports.helmchart.gardener-installer-controller.chartRepository }}
            version: {{ .imports.gardener-installer-controller.version }}
            kubeconfig: {{ .imports.kubeconfig }}
            values:
              abc: ccc
    {{ end }}

#    - name: stuff
#      type: Script
#      dependencies: ["abc"]
#      config:
#        script: |
#          doStuff()
#          createHelmDeployItem()
#          getExportsOfDeployItem()
#          createExport()
    - name: migration_
      type: script
      config: abc

    - name: test
      type: replace
      old:
      - name: stuff
        type: Script
        dependencies: ["abc"]
        config:
          script: |
            doStuff()
            createHelmDeployItem()
            getExportsOfDeployItem()
            createExport()
      migration:
        name: migrate
        type: Script
      new:
      - name: stuff
        type: Helm
        dependencies: ["abc"]
        config:
          script: |
            doStuff()
            createHelmDeployItem()
            getExportsOfDeployItem()
            createExport()

    {{ const abc := range .imports.value }}
    - name: gardener
      type: gardener
      depenencies: [ "stuff", "abc" ]
      config:
        values: abc
    {{ end }}