apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint
metadata:
  name: nginx-ingress-controller
spec:

  imports:
  - key: .kubeconfig
    type: kubeconfig

  - key: .helmchart.ingress-controller
    type: helmchart
  - key: .images.nginx-ingress-controller
    type: image

  - key: .dnsClass
    type: string
    required: false
    imports:
      - abc: val

  - key: .resources
    type: ResourceRequirements
    required: false

  - key: .target
    type: string

  exports:
  - key: ingressClass # from effective helm values as DeployItem's export
    type: string

  executor: |  # has to be idempotent
    - name: migration
      type: container
      config:
        image: my-migration-code-image
    - name: deploy
      type: helm
      config:
        chartRepository: {{ .imports.helmchart.ingress.controller.chartRepository }}
        version: {{ .imports.helmchart.ingress.controller.version }}
        kubeconfig: {{ .imports.kubeconfig }}
        values:
          ingressClass: nginx
          image:
            repository: {{ .imports.images.nginx-ingress-controller.repository }}
            tag: {{ .imports.images.nginx-ingress-controller.tag }}
          dnsControllerClass: {{ .imports.dnsClass }}
          {{ if .imports.resources }}
          resources:
            requests:
              cpu: {{ .imports.resources.requests.cpu }}
              memory: {{ .imports.resources.requests.memory }}
          {{ end }}
        exportsManifest:
        - jsonPath: .spec.config
          key: ingressClass
          resource:
            apiVersion: v1
            kind: Secret
            name: my-secret
            namespace: a
    - name: deploy-2
      type: helm
      config:
        values: {{ .exports.myvalue }}
