apiVersion: landscaper.gardener.cloud/v1alpha1
kind: DeployItem
metadata:
  name: my-component-definition
spec:

  type: container | helm | manifest

  import:
    secretRef:
      name: secret-item1
      key: key

  providerConfig:
    xxx: abc

status:
  phase: Reconciled
  conditions:
  - condition1: healthy
    message: testing

  configGeneration: 2

  exports:
    value: xxx
    secretRef: abc
