apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deployer.fullname" . }}-config
  labels:
    {{- include "deployer.labels" . | nindent 4 }}
data:
  config.yaml: {{ include "deployer-config" . | b64enc }}
