apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: root-1
  namespace: {{ .Namespace }}
spec:

  blueprint:
    ref:
      repositoryContext:
        type: local
        baseUrl: "./"
      version: 1.0.0
      componentName: root
      kind: localResource
      resourceName: root-a

  imports:
    data:
    - name: imp-a
      dataRef: root.key1

  exports:
    data:
    - name: exp-a
      dataRef: exp-a
