{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "landscaper.fullname" . }}
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
rules:
- apiGroups:
  - landscaper.gardener.cloud
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - get
  - list
  - watch
{{- if has "container" .Values.landscaper.deployers }}
- apiGroups:
  - ""
  resources:
  - "pod"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "pod/status"
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - "pods"
  - "pods/status"
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - "serviceaccounts"
  verbs:
  - get
  - list
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "*"
{{- end }}
{{- if has "helm" .Values.landscaper.deployers }}
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "*"
{{- end }}
{{- end }}
